openapi: 3.0.1
info:
  title: Domain Tools Plugin
  description: A plugin that allows the user to query whois and DNS records using ChatGPT. Ask domain name first and which if it will be a whois or DNS query. If it is DNS query, ask what is record type like A, MX, NS, or SOA etc.
  version: 'v1'
servers:
  - url: PLUGIN_HOSTNAME
paths:
  /whois/{domain}:
    get:
      operationId: getWhois
      summary: Get the whois records for domain.
      parameters:
      - in: path
        name: domain
        schema:
            type: string
        required: true
        description: Domain name to be used in query.
      responses:
        "200":
          description: '{"result": {"domain_name": "EMRESAVAS.COM", "registrar": "Google LLC", "whois_server": "whois.google.com", "referral_url": null, "updated_date": "2022-07-28 19:43:50", "creation_date": "2007-08-07 14:44:42", "expiration_date": "2031-08-07 14:44:42", "name_servers": ["IGOR.NS.CLOUDFLARE.COM", "ROXY.NS.CLOUDFLARE.COM"], "status": "clientTransferProhibited https://icann.org/epp#clientTransferProhibited", "emails": "registrar-abuse@google.com", "dnssec": "unsigned", "name": null, "org": null, "address": null, "city": null, "state": null, "zipcode": null, "country": null}}'
  /dns/{record}/{domain}:
    get:
      operationId: getDNS
      summary: Get the DNS records for domain.
      parameters:
      - in: path
        name: record
        schema:
            type: string
        required: true
        description: Record type like A, MX, NS, or SOA etc to be used in query.
      - in: path
        name: domain
        schema:
            type: string
        required: true
        description: Domain name to be used in query.
      responses:
        "200":
          description: '{ "results": [ { "ipAddress": "188.114.96.2" }, { "ipAddress": "188.114.97.2" } ], "processResponseTime": "35ms", "domain": "emresavas.com", "requestType": "A", "warnings": [] }'